#pragma once

#include <iostream>
#include <string>

namespace ICGUtils {

    /**
     * @brief Take a given typename and modify it so that it can be used in a variable name.
     * @note Types are often used as variable names in the code generated by ICG, so we need to
     *          create a version that follow variable name character rules and also won't collide with anything.
     *          Since these are in generated code, they don't have to be pretty, but they should be readable
     *          As a kindness to myself and future Trick developers
     * 
     * @param typename_to_modify 
     * @return std::string version of the type that can be used in a varname
     */
    std::string makeVarname(const std::string& typename_to_modify);

    /**
     * @brief Make the name of the output header file. For now, this is just io_<header_name>
     * 
     * @param header_name input header name
     * @return std::string output header name
     */
    std::string makeIOHeaderName (std::string header_name);

    /**
     * @brief Is the typename an STL container?
     * 
     * @param some_typename name of a type 
     * @return true if it is, false otherwise
     */
    bool isStlContainer (std::string some_typename);
}